//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutureTechBizsoftAssignment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dept_Mas_Tbl
    {
        public int DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public int SORT_NO { get; set; }
    }
}
