//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutureTechBizsoftAssignment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Salary_Tbl
    {
        public int SEQ_NO { get; set; }
        public int EMP_CODE { get; set; }
        public string MONTH { get; set; }
        public int SALARY { get; set; }
        public string COMMENTS { get; set; }
    }
}
