//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutureTechBizsoftAssignment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Mas_Tbl
    {
        public int EMP_CODE { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string FULL_NAME { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime JOIN_DATE { get; set; }
        public int CITY_CODE { get; set; }
        public int DEPT_CODE { get; set; }
    }
}
