//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutureTechBizsoftAssignment.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FutureTechBizsoftLLPEntities : DbContext
    {
        public FutureTechBizsoftLLPEntities()
            : base("name=FutureTechBizsoftLLPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City_Mas_Tbl> City_Mas_Tbl { get; set; }
        public virtual DbSet<Dept_Mas_Tbl> Dept_Mas_Tbl { get; set; }
        public virtual DbSet<Emp_Mas_Tbl> Emp_Mas_Tbl { get; set; }
        public virtual DbSet<Emp_Salary_Tbl> Emp_Salary_Tbl { get; set; }
    
        public virtual ObjectResult<uspgetemployeelist_Result> uspgetemployeelist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspgetemployeelist_Result>("uspgetemployeelist");
        }
    
        public virtual ObjectResult<uspgetsalary_Result> uspgetsalary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspgetsalary_Result>("uspgetsalary");
        }
    }
}
